# Generated by Django 4.1.6 on 2023-03-01 17:38

from django.db import migrations, models
import django.db.models.deletion
import mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mentorship", "0003_create_model_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "specialization",
                    models.ForeignKey(
                        default="specialization",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="mentorship.specialization",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mentorship.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
            bases=(models.Model, mixins.DateTimeMixin),
        ),
    ]
