# Generated by Django 4.1.6 on 2023-02-27 16:43

import django.db.models.deletion
import mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentorship", "0001_create_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            bases=(models.Model, mixins.DateTimeMixin),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience",
                    models.IntegerField(verbose_name="Experience in specialization"),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        default="specialization",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="mentorship.specialization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teachers",
            },
            bases=(models.Model, mixins.DateTimeMixin),
        ),
    ]
